In [1]:
# source: https://www.kaggle.com/lewisfogden/the-life-modelling-problem

import modelx as mx

space = mx.new_space("sample")

In [2]:
space.q = {
    0: 0.001,
    1: 0.002,
    2: 0.003,
    3: 0.003,
    4: 0.004,
    5: 0.004,
    6: 0.005,
    7: 0.007,
    8: 0.009,
    9: 0.011
}

space.w = {
    0: 0.05,
    1: 0.07,
    2: 0.08,
    3: 0.10,
    4: 0.14,
    5: 0.20,
    6: 0.20,
    7: 0.20,
    8: 0.10,
    9: 0.04
}

space.P = 100
space.S = 25000
space.T = 10

In [3]:
@mx.defcells
def num_in_force(t):
    if t == 0:
        return 1
    elif t >= T:
        return 0
    else:
        return num_in_force(t-1) - num_deaths(t-1) - num_lapses(t-1)

@mx.defcells
def num_deaths(t):
    if t < T:
        return num_in_force(t) * q[t]
    else:
        return 0

@mx.defcells
def num_lapses(t):
    if t < T:
        return num_in_force(t) * w[t]
    else:
        return 0

@mx.defcells
def claims(t):
    return num_deaths(t) * S

@mx.defcells
def premiums(t):
    return num_in_force(t) * P

@mx.defcells
def net_cashflow(t):
    return premiums(t) - claims(t)

In [4]:

def npv(cashflow, term, int_rate):
    return sum(cashflow(t) / (1 + int_rate) ** (t+1) for t in range(term))


In [5]:
%timeit npv(net_cashflow, 10, 0.02)

75.3 µs ± 3.35 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
npv(net_cashflow, 10, 0.02)

50.32483075503679

## Dependency Trace

In [7]:
net_cashflow.preds(6)

[Model1.sample.premiums(t=6)=49.35859623121889,
 Model1.sample.claims(t=6)=61.69824528902361]

In [8]:
premiums.succs(6)

[Model1.sample.net_cashflow(t=6)=-12.33964905780472]

## Vectorization

In [9]:
import numpy as np

space.np = np

In [10]:
@mx.defcells
def num_in_force(t):
    if t == 0:
        return np.ones(10000)
    elif t >= T:
        return np.zeros(10000)
    else:
        return num_in_force(t-1) - num_deaths(t-1) - num_lapses(t-1)

In [11]:
npv(net_cashflow, 10, 0.02)

array([50.32483076, 50.32483076, 50.32483076, ..., 50.32483076,
       50.32483076, 50.32483076])

## Varying terms

In [12]:
last_t = np.full(shape=10000, fill_value=10)

last_t[1] = 5    # second policy

last_t

array([10,  5, 10, ..., 10, 10, 10])

In [13]:
space.last_t = last_t

In [14]:
@mx.defcells
def num_maturities(t):
    return (t == last_t) * (num_in_force(t-1) - num_deaths(t-1) - num_lapses(t-1))

In [15]:
num_maturities(5)

array([0.        , 0.62008287, 0.        , ..., 0.        , 0.        ,
       0.        ])

In [16]:
@mx.defcells
def num_in_force(t):
    if t == 0:
        return np.ones(10000)
    elif t >= T:
        return np.zeros(10000)
    else:
        return num_in_force(t-1) - num_deaths(t-1) - num_lapses(t-1) - num_maturities(t)

In [17]:
num_in_force(5)

array([0.62008287, 0.        , 0.62008287, ..., 0.62008287, 0.62008287,
       0.62008287])

In [18]:
net_cashflow(6)

array([-12.33964906,   0.        , -12.33964906, ..., -12.33964906,
       -12.33964906, -12.33964906])

In [19]:
npv(net_cashflow, 10, 0.02)

array([ 50.32483076, 158.53568283,  50.32483076, ...,  50.32483076,
        50.32483076,  50.32483076])

## Deep recursion example

In [20]:
@mx.defcells
def recursive(t):
    if t == 0:
        return 0
    else:
        return recursive(t-1)

In [21]:
recursive(50000)

0